require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/NestedMethodDefinition:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*.rake"
    - "config/**/*.rb"
    - "Gemfile"
    - "Rakefile"
    - "spec/**/*.rb"

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - "config/routes.rb"
    - "Gemfile"
    - "lib/**/*.gemspec"
    - "spec/**/*.rb"
    - "db/seeds.rb"
  Max: 120

Metrics/MethodLength:
  Enabled: false

Naming/PredicateName:
  NamePrefixBlacklist:
    - is_

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '{}'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
